# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
#
# ===================================================================

spring:
  application:
    name: chemical
  jackson:
    serialization:
      indent-output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${RAPIDTOX_CONNECTION_STRING}
    username: ${RAPIDTOX_USER}
    password: ${RAPIDTOX_PASSWORD}
    hikari:
      poolName: Hikari
      auto-commit: false
      minimum-idle: 2
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      #hibernate.default_schema: ccd_app
# Logging
logging:
  level:
    gov.epa.ccte.api.*: info
    org.springframework: warn

# server
server:
  servlet:
    context-path: /
  #port: 9300

# sentry
sentry:
  dsn: https://12b483f1fc1741fd8609653eed0d2190@ccte-app-monitoring.epa.gov/12
  # Set traces-sample-rate to 1.0 to capture 100% of transactions for performance monitoring.
  # We recommend adjusting this value in production.
  traces-sample-rate: 1.0
  environment: dev

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
# multiple datasources
#app:
#  datasource:
#    pgsql:
#      type: com.zaxxer.hikari.HikariDataSource
#      url: (connection goes here)
#      username: (user goes here)
#      password: (pw goes here)
